### ISSUE TITLE
Troubles including Cuztom

### ISSUE THREAD

**Issue by vicnentq76** [gizburdt/cuztom#371]
Hi everyone,

Everything is told in the title, I've got big troubles trying to include Cuztom in my Wordpress theme.

Here's my process :
   - i copy the folder 'cuztom-master' in my theme's 'inc' folder
   - i go to the functions.php file where i include the cuztom.php file ( i tried several things like` require_once( get_stylesheet_directory() . '/inc/cuztom-master/cuztom.php' )` or `include('inc/cuztom-master/cuztom.php')` )
   - i create a personal file called 'custom_types.php' in which i will put my own code

So far everything is ok except i don't know if the files are really included.
Then i put this first line in my personnal file : `$client = register_cuztom_post_type('Client');`
And there nothing happens, or sometimes i don't even see my files in the editor no more...

I found this process in a tutorial. Can somebody help me ?
I must have missed something in installation...

Thanks !

**Comment by gizburdt** [comment]
Hi!

Let's see. I think you're including the files the right way. As you can see on this page, https://cuztom.readme.io/, an include will work, but your `require_once( get_stylesheet_directory() . '/inc/cuztom-master/cuztom.php' )` should work too.

Creating a custom_types.php is a good practice. Is this file also included in your `functions.php`?

And the last thing, you need to wrap all Cuztom code in an `add_action('init', [function])`, like so:

```
function content_types()
{
    // Content types
}
add_action( 'init', 'content_types' );
```

Hope this will help, otherwise let me know! :)

**Comment by gizburdt** [comment]
Did it work? :)

**Comment by vicnentq76** [comment]
Couldn't test if for the moment !

**Comment by gizburdt** [comment]
Ok, let me know when you tried it.

**Comment by vicnentq76** [comment]
In fact, I completely changed my method : I do it entirely with code now without cuztom... For the reason that when i include the library, mywordpress is getting mad : many functionnalities are disapearing !!! For exemple i can't access to the medias anymore ! I need to disable my child theme (reactivate the parent) to make it word again... I suppose this is an problem of compatilibity between the theme and cuztom ?!

**Comment by gizburdt** [comment]
That's sad to hear. I do not recognize these problems, unfortunately. If you have any problems in the future, let me know :)
